version: "3.3"

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=enrique
      - POSTGRES_PASSWORD=rootxd
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=enrique@mail.com
      - PGADMIN_DEFAULT_PASSWORD=rootxd
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootxd
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
